version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/express-typescript
    working_dir: /var/www/express-typescript
    command: npm run dev